### ISSUE TITLE
edfapi.dll quarantined by by Symantec Endpoint 

### ISSUE THREAD

**Issue by ftadel** [tz-lom/eyelinkReader#1]
FYI: One of our users reported this to us: 
http://neuroimage.usc.edu/forums/t/two-brainstorm-files-identified-as-virus/5596

**Comment by tz-lom** [comment]
Thank you for the report, I think that the problem is in Symantec and this is a false positive alarm. 
Can you please clarify are you really use my library in Brainstorm?
I have no problems with that, but I am surprised that you use R code in Matlab library. 
Also I want to mention that I am not a developer of this DLL.

**Comment by ftadel** [comment]
Sorry, I posted this message at the wrong place, indeed...
Do you know who I should contact about edfapi.dll?

**Comment by tz-lom** [comment]
No problem
The DLL created by SR Research, they have forum https://www.sr-support.com/forum
Actually, I think the best way to deal with that problem is to report false positive to Symantec, so I created a report on their website.

**Comment by tz-lom** [comment]
Symantec confirmed false positive and will remove signature from database within 24 hours.

**Comment by ftadel** [comment]
Thanks for following up on this!
